In [1]:
# Load the cars dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

df = pd.read_csv('cars.csv')
df.head(20)
df

,price,name,yearOfRegistration,monthOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,vehicleType
0,400,Ford_Escort,1992,8,manuell,89,escort,60000,benzin,ford,kombi
1,3500,Bmw_320_cabrio,1996,0,manuell,150,3er,125000,NaN,bmw,cabrio
2,2200,Mercedes_C_230_T_im_top_Zustand_Tuev_Neu!!_Win...,1998,0,manuell,150,c_klasse,150000,benzin,mercedes_benz,kombi
3,4000,A3_Limousine,2006,7,manuell,0,a3,150000,diesel,audi,limousine
4,2600,Smart_Smart_cabrio_450_cdi,2002,7,automatik,41,fortwo,150000,diesel,smart,cabrio
5,2222,BMW_318ti_compact,2001,10,manuell,143,3er,150000,benzin,bmw,limousine
6,4000,Toyota_Yaris_1.0_VVT_i,2008,11,manuell,69,yaris,125000,benzin,toyota,kleinwagen
7,570,Audi_A4_B5_2_5TDi_Quattro_Chip_Gewindefahrwerk...,1999,6,manuell,180,a4,150000,diesel,audi,kombi
8,9999,Golf_5_GTI_2.0L_TFSI,2005,10,manuell,200,golf,150000,benzin,volkswagen,kleinwagen
9,16999,VW_Multivan_Comfortline,2006,1,manuell,131,transporter,150000,diesel,volkswagen,bus
10,11300,Mercedes_Benz_SLK_320,2000,3,manuell,218,slk,90000,benzin,mercedes_benz,cabrio
11,11980,Mercedes_Benz_CLS_350_7G_TRONIC,2005,8,automatik,272,andere,125000,benzin,mercedes_benz,coupe
12,3999,Volkswagen_Golf_1.4_Comfortline,2006,10,manuell,80,golf,100000,benzin,volkswagen,limousine
13,500,Verkaufe_meinen_Goldi,1997,0,manuell,1256,NaN,150000,NaN,audi,kleinwagen
14,3450,Opel_Zafira_1.9_CDTI,2006,11,manuell,120,zafira,150000,diesel,opel,bus
15,149500,Ferrari_458_Italia___Garantie_bis_November_2016,2010,11,automatik,570,NaN,20000,benzin,sonstige_autos,coupe
16,500,Zuverlaessiger_Opel_Corsa_B_abzugeben!!,1997,3,manuell,60,corsa,150000,benzin,opel,kleinwagen
17,12250,Volkswagen_Golf_1.2_TSI_BlueMotion_Technology_...,2012,2,automatik,105,golf,50000,benzin,volkswagen,limousine
18,500,Twingo_Schnaeppchen_nur_noch_bis_Montag_angeme...,2017,0,manuell,0,twingo,150000,benzin,renault,NaN
19,199,Opel_B_Corsa_zu_verkaufen,2000,0,manuell,60,corsa,150000,NaN,opel,NaN
20,2800,Seat_Arosa_Bj._2004,2004,8,manuell,50,arosa,70000,benzin,seat,kleinwagen
21,7399,Volkswagen_Passat_Variant_2.0_TDI_DPF_DSG_Indi...,2007,10,automatik,140,passat,150000,diesel,volkswagen,kombi
22,1000,Schoen_gepflegt_und_gut_aussehend_?,1999,0,NaN,0,mx_reihe,5000,NaN,mazda,limousine
23,2200,Opel_Corsa_1.0_12V,2005,1,manuell,60,corsa,80000,benzin,opel,kleinwagen
24,5500,Verkaufe_Peugeot_206_+__Generation_75_t,2012,4,manuell,73,2_reihe,50000,benzin,peugeot,limousine
25,5000,Toyota_RAV_4_4x4,2000,8,manuell,150,rav,150000,benzin,toyota,suv
26,17800,FORD_MONDEO_Bussines_Turnier____Kombi___Diesel...,2013,9,automatik,163,mondeo,60000,diesel,ford,kombi
27,19800,Toyota_Land_Cruiser_FJ40_Benzin,1978,6,manuell,135,andere,125000,benzin,toyota,suv
28,5299,Volkswagen_Volkswagen_Golf_1.9_TDI___AHK___DPF...,2004,11,manuell,105,golf,150000,diesel,volkswagen,limousine
29,1000,Audi_A4_zu_Verkaufen,1995,12,manuell,101,a4,150000,benzin,audi,limousine
...,...,...,...,...,...,...,...,...,...,...,...
9970,6350,Mercedes_Benz_C_180_Kompressor_Automatik_Classic,2004,7,automatik,143,c_klasse,150000,benzin,mercedes_benz,limousine
9971,990,Opel_Astra_1.6_Comfort,1999,11,manuell,101,astra,150000,benzin,opel,limousine
9972,8495,Volkswagen_Golf_Plus_1.6_Automatik_Comfortline,2006,11,automatik,102,golf,80000,benzin,volkswagen,bus
9973,1650,BMW_528i_Automatik_TÜV_04/17,1996,4,automatik,193,5er,150000,benzin,bmw,limousine
9974,1690,Opel_Astra_1.6,2001,9,manuell,0,astra,150000,benzin,opel,kleinwagen
9975,3999,Ford_Mondeo_3.0_V6_ST_220,2004,10,manuell,226,mondeo,150000,benzin,ford,limousine
9976,5190,Opel_Meriva_1.6_16V,2008,4,manuell,105,meriva,150000,benzin,opel,bus
9977,2210,A4_Avant_1.9_TDI_MMI_TV_Bose_DPF_Xenon_Carbon,2002,11,manuell,131,a4,150000,diesel,audi,kombi
9978,7399,Polo_6r__1_2,2018,2,manuell,55,polo,30000,benzin,volkswagen,NaN
9979,1499,Mazda_Premacy_1.9_Exclusiv,2002,11,manuell,101,andere,150000,benzin,mazda,bus
9980,2399,Mercedes_Benz_E_200_T__S210__Avantgarde__Xenon...,1998,7,manuell,136,e_klasse,150000,benzin,mercedes_benz,kombi
9981,599,VW_Golf_III_GL_Automatik__Preis_Verhandlungsba...,1993,4,automatik,75,golf,150000,benzin,volkswagen,kleinwagen
9982,2650,VW_Fox_Bj.2005,2005,6,manuell,52,fox,100000,benzin,volkswagen,kleinwagen
9983,8950,AlfaRomeo_Spider_2_4l_JTDM_EXCLUSIVE_:_schwarz...,2007,4,manuell,200,spider,150000,diesel,alfa_romeo,cabrio
9984,15900,VW_Passat_Variant_Comfortline,2012,4,manuell,140,passat,70000,diesel,volkswagen,kombi
9985,3250,Opel_Zafira_1.6_CNG_Njoy,2005,7,manuell,97,zafira,125000,cng,opel,bus
9986,470,Ford_Ka_mit_Tuev,1999,0,manuell,50,ka,70000,benzin,ford,kleinwagen
9987,450,Fiat_Seicento_1.1_Benziner,2001,2,manuell,55,seicento,125000,benzin,fiat,kleinwagen
9988,1800,Volkswagen_Passat_Variant_1.8_5V,1998,10,manuell,125,passat,150000,benzin,volkswagen,kombi
9989,3600,Vw_t4_TDI_2.5_l_transporter_caravelle_lkw_TÜV_...,2001,2,manuell,102,transporter,150000,diesel,volkswagen,bus
9990,3800,Ford_Galaxy,2005,3,manuell,90,galaxy,5000,NaN,ford,NaN
9991,1899,Vw_T2a_Westfalia_Karosse_Bj.70_rollbar_auf_Ach...,1970,0,NaN,0,transporter,150000,benzin,volkswagen,bus
9992,2600,Ford_Fusion_1.25_Ambiente_2.Hand__Zahnriemen_&...,2006,3,manuell,75,fusion,150000,benzin,ford,kleinwagen
9993,5190,Volkswagen_Golf_1.9_TDI_Tour_Edition,2007,10,manuell,105,golf,150000,diesel,volkswagen,limousine
9994,5200,Volkswagen_Golf_Plus_1.9_TDI,2005,12,manuell,90,golf,150000,diesel,volkswagen,bus
9995,2650,Opel_Corsa_C_1.2_Twinport,2005,1,manuell,80,corsa,150000,benzin,opel,kleinwagen
9996,9600,Volkswagen_Touran_2.0_TDI_DPF,2011,6,manuell,140,touran,150000,diesel,volkswagen,bus
9997,1500,Suche_zuverlaessigen_Kombi,1999,0,NaN,101,astra,150000,NaN,opel,kombi
9998,970,Renault_Twingo,2002,10,manuell,58,twingo,150000,benzin,renault,kleinwagen
9999,7990,Renault_Megane_1.6_16V_100_Authentique,2012,4,manuell,101,megane,60000,benzin,renault,limousine

In [2]:
# Check for NaN values
df.isnull().any()

price                  False
name                   False
yearOfRegistration     False
monthOfRegistration    False
gearbox                 True
powerPS                False
model                   True
kilometer              False
fuelType                True
brand                  False
vehicleType             True
dtype: bool

In [3]:
# Fill the NaN values

from statistics import mode
df['gearbox']=df['gearbox'].fillna(mode(df['gearbox']))
df['model']=df['model'].fillna(mode(df['model']))
df['fuelType']=df['fuelType'].fillna(mode(df['fuelType']))
df['vehicleType']=df['vehicleType'].fillna(mode(df['vehicleType']))
df.head(30)

,price,name,yearOfRegistration,monthOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,vehicleType
0,400,Ford_Escort,1992,8,manuell,89,escort,60000,benzin,ford,kombi
1,3500,Bmw_320_cabrio,1996,0,manuell,150,3er,125000,benzin,bmw,cabrio
2,2200,Mercedes_C_230_T_im_top_Zustand_Tuev_Neu!!_Win...,1998,0,manuell,150,c_klasse,150000,benzin,mercedes_benz,kombi
3,4000,A3_Limousine,2006,7,manuell,0,a3,150000,diesel,audi,limousine
4,2600,Smart_Smart_cabrio_450_cdi,2002,7,automatik,41,fortwo,150000,diesel,smart,cabrio
5,2222,BMW_318ti_compact,2001,10,manuell,143,3er,150000,benzin,bmw,limousine
6,4000,Toyota_Yaris_1.0_VVT_i,2008,11,manuell,69,yaris,125000,benzin,toyota,kleinwagen
7,570,Audi_A4_B5_2_5TDi_Quattro_Chip_Gewindefahrwerk...,1999,6,manuell,180,a4,150000,diesel,audi,kombi
8,9999,Golf_5_GTI_2.0L_TFSI,2005,10,manuell,200,golf,150000,benzin,volkswagen,kleinwagen
9,16999,VW_Multivan_Comfortline,2006,1,manuell,131,transporter,150000,diesel,volkswagen,bus
10,11300,Mercedes_Benz_SLK_320,2000,3,manuell,218,slk,90000,benzin,mercedes_benz,cabrio
11,11980,Mercedes_Benz_CLS_350_7G_TRONIC,2005,8,automatik,272,andere,125000,benzin,mercedes_benz,coupe
12,3999,Volkswagen_Golf_1.4_Comfortline,2006,10,manuell,80,golf,100000,benzin,volkswagen,limousine
13,500,Verkaufe_meinen_Goldi,1997,0,manuell,1256,golf,150000,benzin,audi,kleinwagen
14,3450,Opel_Zafira_1.9_CDTI,2006,11,manuell,120,zafira,150000,diesel,opel,bus
15,149500,Ferrari_458_Italia___Garantie_bis_November_2016,2010,11,automatik,570,golf,20000,benzin,sonstige_autos,coupe
16,500,Zuverlaessiger_Opel_Corsa_B_abzugeben!!,1997,3,manuell,60,corsa,150000,benzin,opel,kleinwagen
17,12250,Volkswagen_Golf_1.2_TSI_BlueMotion_Technology_...,2012,2,automatik,105,golf,50000,benzin,volkswagen,limousine
18,500,Twingo_Schnaeppchen_nur_noch_bis_Montag_angeme...,2017,0,manuell,0,twingo,150000,benzin,renault,limousine
19,199,Opel_B_Corsa_zu_verkaufen,2000,0,manuell,60,corsa,150000,benzin,opel,limousine
20,2800,Seat_Arosa_Bj._2004,2004,8,manuell,50,arosa,70000,benzin,seat,kleinwagen
21,7399,Volkswagen_Passat_Variant_2.0_TDI_DPF_DSG_Indi...,2007,10,automatik,140,passat,150000,diesel,volkswagen,kombi
22,1000,Schoen_gepflegt_und_gut_aussehend_?,1999,0,manuell,0,mx_reihe,5000,benzin,mazda,limousine
23,2200,Opel_Corsa_1.0_12V,2005,1,manuell,60,corsa,80000,benzin,opel,kleinwagen
24,5500,Verkaufe_Peugeot_206_+__Generation_75_t,2012,4,manuell,73,2_reihe,50000,benzin,peugeot,limousine
25,5000,Toyota_RAV_4_4x4,2000,8,manuell,150,rav,150000,benzin,toyota,suv
26,17800,FORD_MONDEO_Bussines_Turnier____Kombi___Diesel...,2013,9,automatik,163,mondeo,60000,diesel,ford,kombi
27,19800,Toyota_Land_Cruiser_FJ40_Benzin,1978,6,manuell,135,andere,125000,benzin,toyota,suv
28,5299,Volkswagen_Volkswagen_Golf_1.9_TDI___AHK___DPF...,2004,11,manuell,105,golf,150000,diesel,volkswagen,limousine
29,1000,Audi_A4_zu_Verkaufen,1995,12,manuell,101,a4,150000,benzin,audi,limousine

In [4]:
df.replace({'gearbox':{'manuell':'manual','automatik':'automatic'}},inplace=True)
df.replace({'vehicleType':{'kleinwagen':'small_car','kombi':'combi','andere':'Others'}},inplace=True)
df.replace({'fuelType':{'benzin':'petrol','andere':'others','elektro':'electro'}},inplace=True)
df

,price,name,yearOfRegistration,monthOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,vehicleType
0,400,Ford_Escort,1992,8,manual,89,escort,60000,petrol,ford,combi
1,3500,Bmw_320_cabrio,1996,0,manual,150,3er,125000,petrol,bmw,cabrio
2,2200,Mercedes_C_230_T_im_top_Zustand_Tuev_Neu!!_Win...,1998,0,manual,150,c_klasse,150000,petrol,mercedes_benz,combi
3,4000,A3_Limousine,2006,7,manual,0,a3,150000,diesel,audi,limousine
4,2600,Smart_Smart_cabrio_450_cdi,2002,7,automatic,41,fortwo,150000,diesel,smart,cabrio
5,2222,BMW_318ti_compact,2001,10,manual,143,3er,150000,petrol,bmw,limousine
6,4000,Toyota_Yaris_1.0_VVT_i,2008,11,manual,69,yaris,125000,petrol,toyota,small_car
7,570,Audi_A4_B5_2_5TDi_Quattro_Chip_Gewindefahrwerk...,1999,6,manual,180,a4,150000,diesel,audi,combi
8,9999,Golf_5_GTI_2.0L_TFSI,2005,10,manual,200,golf,150000,petrol,volkswagen,small_car
9,16999,VW_Multivan_Comfortline,2006,1,manual,131,transporter,150000,diesel,volkswagen,bus
10,11300,Mercedes_Benz_SLK_320,2000,3,manual,218,slk,90000,petrol,mercedes_benz,cabrio
11,11980,Mercedes_Benz_CLS_350_7G_TRONIC,2005,8,automatic,272,andere,125000,petrol,mercedes_benz,coupe
12,3999,Volkswagen_Golf_1.4_Comfortline,2006,10,manual,80,golf,100000,petrol,volkswagen,limousine
13,500,Verkaufe_meinen_Goldi,1997,0,manual,1256,golf,150000,petrol,audi,small_car
14,3450,Opel_Zafira_1.9_CDTI,2006,11,manual,120,zafira,150000,diesel,opel,bus
15,149500,Ferrari_458_Italia___Garantie_bis_November_2016,2010,11,automatic,570,golf,20000,petrol,sonstige_autos,coupe
16,500,Zuverlaessiger_Opel_Corsa_B_abzugeben!!,1997,3,manual,60,corsa,150000,petrol,opel,small_car
17,12250,Volkswagen_Golf_1.2_TSI_BlueMotion_Technology_...,2012,2,automatic,105,golf,50000,petrol,volkswagen,limousine
18,500,Twingo_Schnaeppchen_nur_noch_bis_Montag_angeme...,2017,0,manual,0,twingo,150000,petrol,renault,limousine
19,199,Opel_B_Corsa_zu_verkaufen,2000,0,manual,60,corsa,150000,petrol,opel,limousine
20,2800,Seat_Arosa_Bj._2004,2004,8,manual,50,arosa,70000,petrol,seat,small_car
21,7399,Volkswagen_Passat_Variant_2.0_TDI_DPF_DSG_Indi...,2007,10,automatic,140,passat,150000,diesel,volkswagen,combi
22,1000,Schoen_gepflegt_und_gut_aussehend_?,1999,0,manual,0,mx_reihe,5000,petrol,mazda,limousine
23,2200,Opel_Corsa_1.0_12V,2005,1,manual,60,corsa,80000,petrol,opel,small_car
24,5500,Verkaufe_Peugeot_206_+__Generation_75_t,2012,4,manual,73,2_reihe,50000,petrol,peugeot,limousine
25,5000,Toyota_RAV_4_4x4,2000,8,manual,150,rav,150000,petrol,toyota,suv
26,17800,FORD_MONDEO_Bussines_Turnier____Kombi___Diesel...,2013,9,automatic,163,mondeo,60000,diesel,ford,combi
27,19800,Toyota_Land_Cruiser_FJ40_Benzin,1978,6,manual,135,andere,125000,petrol,toyota,suv
28,5299,Volkswagen_Volkswagen_Golf_1.9_TDI___AHK___DPF...,2004,11,manual,105,golf,150000,diesel,volkswagen,limousine
29,1000,Audi_A4_zu_Verkaufen,1995,12,manual,101,a4,150000,petrol,audi,limousine
...,...,...,...,...,...,...,...,...,...,...,...
9970,6350,Mercedes_Benz_C_180_Kompressor_Automatik_Classic,2004,7,automatic,143,c_klasse,150000,petrol,mercedes_benz,limousine
9971,990,Opel_Astra_1.6_Comfort,1999,11,manual,101,astra,150000,petrol,opel,limousine
9972,8495,Volkswagen_Golf_Plus_1.6_Automatik_Comfortline,2006,11,automatic,102,golf,80000,petrol,volkswagen,bus
9973,1650,BMW_528i_Automatik_TÜV_04/17,1996,4,automatic,193,5er,150000,petrol,bmw,limousine
9974,1690,Opel_Astra_1.6,2001,9,manual,0,astra,150000,petrol,opel,small_car
9975,3999,Ford_Mondeo_3.0_V6_ST_220,2004,10,manual,226,mondeo,150000,petrol,ford,limousine
9976,5190,Opel_Meriva_1.6_16V,2008,4,manual,105,meriva,150000,petrol,opel,bus
9977,2210,A4_Avant_1.9_TDI_MMI_TV_Bose_DPF_Xenon_Carbon,2002,11,manual,131,a4,150000,diesel,audi,combi
9978,7399,Polo_6r__1_2,2018,2,manual,55,polo,30000,petrol,volkswagen,limousine
9979,1499,Mazda_Premacy_1.9_Exclusiv,2002,11,manual,101,andere,150000,petrol,mazda,bus
9980,2399,Mercedes_Benz_E_200_T__S210__Avantgarde__Xenon...,1998,7,manual,136,e_klasse,150000,petrol,mercedes_benz,combi
9981,599,VW_Golf_III_GL_Automatik__Preis_Verhandlungsba...,1993,4,automatic,75,golf,150000,petrol,volkswagen,small_car
9982,2650,VW_Fox_Bj.2005,2005,6,manual,52,fox,100000,petrol,volkswagen,small_car
9983,8950,AlfaRomeo_Spider_2_4l_JTDM_EXCLUSIVE_:_schwarz...,2007,4,manual,200,spider,150000,diesel,alfa_romeo,cabrio
9984,15900,VW_Passat_Variant_Comfortline,2012,4,manual,140,passat,70000,diesel,volkswagen,combi
9985,3250,Opel_Zafira_1.6_CNG_Njoy,2005,7,manual,97,zafira,125000,cng,opel,bus
9986,470,Ford_Ka_mit_Tuev,1999,0,manual,50,ka,70000,petrol,ford,small_car
9987,450,Fiat_Seicento_1.1_Benziner,2001,2,manual,55,seicento,125000,petrol,fiat,small_car
9988,1800,Volkswagen_Passat_Variant_1.8_5V,1998,10,manual,125,passat,150000,petrol,volkswagen,combi
9989,3600,Vw_t4_TDI_2.5_l_transporter_caravelle_lkw_TÜV_...,2001,2,manual,102,transporter,150000,diesel,volkswagen,bus
9990,3800,Ford_Galaxy,2005,3,manual,90,galaxy,5000,petrol,ford,limousine
9991,1899,Vw_T2a_Westfalia_Karosse_Bj.70_rollbar_auf_Ach...,1970,0,manual,0,transporter,150000,petrol,volkswagen,bus
9992,2600,Ford_Fusion_1.25_Ambiente_2.Hand__Zahnriemen_&...,2006,3,manual,75,fusion,150000,petrol,ford,small_car
9993,5190,Volkswagen_Golf_1.9_TDI_Tour_Edition,2007,10,manual,105,golf,150000,diesel,volkswagen,limousine
9994,5200,Volkswagen_Golf_Plus_1.9_TDI,2005,12,manual,90,golf,150000,diesel,volkswagen,bus
9995,2650,Opel_Corsa_C_1.2_Twinport,2005,1,manual,80,corsa,150000,petrol,opel,small_car
9996,9600,Volkswagen_Touran_2.0_TDI_DPF,2011,6,manual,140,touran,150000,diesel,volkswagen,bus
9997,1500,Suche_zuverlaessigen_Kombi,1999,0,manual,101,astra,150000,petrol,opel,combi
9998,970,Renault_Twingo,2002,10,manual,58,twingo,150000,petrol,renault,small_car
9999,7990,Renault_Megane_1.6_16V_100_Authentique,2012,4,manual,101,megane,60000,petrol,renault,limousine

In [5]:
#Data Cleaning or formatting

#df.name=df.name.str.replace('_',' ')
df.model=df.model.str.replace('_',' ')
df.brand=df.brand.str.replace('_',' ')
df.head(25)

,price,name,yearOfRegistration,monthOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,vehicleType
0,400,Ford_Escort,1992,8,manual,89,escort,60000,petrol,ford,combi
1,3500,Bmw_320_cabrio,1996,0,manual,150,3er,125000,petrol,bmw,cabrio
2,2200,Mercedes_C_230_T_im_top_Zustand_Tuev_Neu!!_Win...,1998,0,manual,150,c klasse,150000,petrol,mercedes benz,combi
3,4000,A3_Limousine,2006,7,manual,0,a3,150000,diesel,audi,limousine
4,2600,Smart_Smart_cabrio_450_cdi,2002,7,automatic,41,fortwo,150000,diesel,smart,cabrio
5,2222,BMW_318ti_compact,2001,10,manual,143,3er,150000,petrol,bmw,limousine
6,4000,Toyota_Yaris_1.0_VVT_i,2008,11,manual,69,yaris,125000,petrol,toyota,small_car
7,570,Audi_A4_B5_2_5TDi_Quattro_Chip_Gewindefahrwerk...,1999,6,manual,180,a4,150000,diesel,audi,combi
8,9999,Golf_5_GTI_2.0L_TFSI,2005,10,manual,200,golf,150000,petrol,volkswagen,small_car
9,16999,VW_Multivan_Comfortline,2006,1,manual,131,transporter,150000,diesel,volkswagen,bus
10,11300,Mercedes_Benz_SLK_320,2000,3,manual,218,slk,90000,petrol,mercedes benz,cabrio
11,11980,Mercedes_Benz_CLS_350_7G_TRONIC,2005,8,automatic,272,andere,125000,petrol,mercedes benz,coupe
12,3999,Volkswagen_Golf_1.4_Comfortline,2006,10,manual,80,golf,100000,petrol,volkswagen,limousine
13,500,Verkaufe_meinen_Goldi,1997,0,manual,1256,golf,150000,petrol,audi,small_car
14,3450,Opel_Zafira_1.9_CDTI,2006,11,manual,120,zafira,150000,diesel,opel,bus
15,149500,Ferrari_458_Italia___Garantie_bis_November_2016,2010,11,automatic,570,golf,20000,petrol,sonstige autos,coupe
16,500,Zuverlaessiger_Opel_Corsa_B_abzugeben!!,1997,3,manual,60,corsa,150000,petrol,opel,small_car
17,12250,Volkswagen_Golf_1.2_TSI_BlueMotion_Technology_...,2012,2,automatic,105,golf,50000,petrol,volkswagen,limousine
18,500,Twingo_Schnaeppchen_nur_noch_bis_Montag_angeme...,2017,0,manual,0,twingo,150000,petrol,renault,limousine
19,199,Opel_B_Corsa_zu_verkaufen,2000,0,manual,60,corsa,150000,petrol,opel,limousine
20,2800,Seat_Arosa_Bj._2004,2004,8,manual,50,arosa,70000,petrol,seat,small_car
21,7399,Volkswagen_Passat_Variant_2.0_TDI_DPF_DSG_Indi...,2007,10,automatic,140,passat,150000,diesel,volkswagen,combi
22,1000,Schoen_gepflegt_und_gut_aussehend_?,1999,0,manual,0,mx reihe,5000,petrol,mazda,limousine
23,2200,Opel_Corsa_1.0_12V,2005,1,manual,60,corsa,80000,petrol,opel,small_car
24,5500,Verkaufe_Peugeot_206_+__Generation_75_t,2012,4,manual,73,2 reihe,50000,petrol,peugeot,limousine

In [6]:
#df.drop('model',axis=1,inplace=True)
#df.drop('brand',axis=1,inplace=True)
df.drop('name',axis=1,inplace=True)
#df.drop('monthOfRegistration',axis=1,inplace=True)
#df.drop('powerPS',axis=1,inplace=True)
#df.drop('model',axis=1,inplace=True)
#df.drop('kilometer',axis=1,inplace=True)
df.head()

,price,yearOfRegistration,monthOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,vehicleType
0,400,1992,8,manual,89,escort,60000,petrol,ford,combi
1,3500,1996,0,manual,150,3er,125000,petrol,bmw,cabrio
2,2200,1998,0,manual,150,c klasse,150000,petrol,mercedes benz,combi
3,4000,2006,7,manual,0,a3,150000,diesel,audi,limousine
4,2600,2002,7,automatic,41,fortwo,150000,diesel,smart,cabrio

In [7]:
df = df.loc[(df.price>400)&(df.price<=40000)]
df = df.loc[(df.yearOfRegistration>1990)&(df.yearOfRegistration<=2016)]
df = df.loc[(df.powerPS>10)]
df = df.loc[(df.kilometer>1000)&(df.kilometer<=150000)]
df

,price,yearOfRegistration,monthOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,vehicleType
1,3500,1996,0,manual,150,3er,125000,petrol,bmw,cabrio
2,2200,1998,0,manual,150,c klasse,150000,petrol,mercedes benz,combi
4,2600,2002,7,automatic,41,fortwo,150000,diesel,smart,cabrio
5,2222,2001,10,manual,143,3er,150000,petrol,bmw,limousine
6,4000,2008,11,manual,69,yaris,125000,petrol,toyota,small_car
7,570,1999,6,manual,180,a4,150000,diesel,audi,combi
8,9999,2005,10,manual,200,golf,150000,petrol,volkswagen,small_car
9,16999,2006,1,manual,131,transporter,150000,diesel,volkswagen,bus
10,11300,2000,3,manual,218,slk,90000,petrol,mercedes benz,cabrio
11,11980,2005,8,automatic,272,andere,125000,petrol,mercedes benz,coupe
12,3999,2006,10,manual,80,golf,100000,petrol,volkswagen,limousine
13,500,1997,0,manual,1256,golf,150000,petrol,audi,small_car
14,3450,2006,11,manual,120,zafira,150000,diesel,opel,bus
16,500,1997,3,manual,60,corsa,150000,petrol,opel,small_car
17,12250,2012,2,automatic,105,golf,50000,petrol,volkswagen,limousine
20,2800,2004,8,manual,50,arosa,70000,petrol,seat,small_car
21,7399,2007,10,automatic,140,passat,150000,diesel,volkswagen,combi
23,2200,2005,1,manual,60,corsa,80000,petrol,opel,small_car
24,5500,2012,4,manual,73,2 reihe,50000,petrol,peugeot,limousine
25,5000,2000,8,manual,150,rav,150000,petrol,toyota,suv
26,17800,2013,9,automatic,163,mondeo,60000,diesel,ford,combi
28,5299,2004,11,manual,105,golf,150000,diesel,volkswagen,limousine
29,1000,1995,12,manual,101,a4,150000,petrol,audi,limousine
30,7800,2005,11,automatic,218,x reihe,150000,diesel,bmw,suv
32,1700,2003,8,manual,83,kalos,100000,petrol,daewoo,small_car
33,750,1994,5,manual,80,corsa,125000,petrol,opel,small_car
34,4200,2003,1,manual,110,a2,150000,petrol,audi,small_car
35,9300,2007,8,manual,205,a4,150000,diesel,audi,combi
36,10500,2005,3,manual,203,a4,150000,diesel,audi,Others
38,5350,2006,10,automatic,163,andere,150000,diesel,hyundai,suv
...,...,...,...,...,...,...,...,...,...,...
9966,899,2000,1,manual,50,arosa,150000,petrol,seat,small_car
9968,4700,2006,1,manual,140,golf,150000,diesel,volkswagen,bus
9969,3450,2005,9,manual,110,micra,125000,petrol,nissan,small_car
9970,6350,2004,7,automatic,143,c klasse,150000,petrol,mercedes benz,limousine
9971,990,1999,11,manual,101,astra,150000,petrol,opel,limousine
9972,8495,2006,11,automatic,102,golf,80000,petrol,volkswagen,bus
9973,1650,1996,4,automatic,193,5er,150000,petrol,bmw,limousine
9975,3999,2004,10,manual,226,mondeo,150000,petrol,ford,limousine
9976,5190,2008,4,manual,105,meriva,150000,petrol,opel,bus
9977,2210,2002,11,manual,131,a4,150000,diesel,audi,combi
9979,1499,2002,11,manual,101,andere,150000,petrol,mazda,bus
9980,2399,1998,7,manual,136,e klasse,150000,petrol,mercedes benz,combi
9981,599,1993,4,automatic,75,golf,150000,petrol,volkswagen,small_car
9982,2650,2005,6,manual,52,fox,100000,petrol,volkswagen,small_car
9983,8950,2007,4,manual,200,spider,150000,diesel,alfa romeo,cabrio
9984,15900,2012,4,manual,140,passat,70000,diesel,volkswagen,combi
9985,3250,2005,7,manual,97,zafira,125000,cng,opel,bus
9986,470,1999,0,manual,50,ka,70000,petrol,ford,small_car
9987,450,2001,2,manual,55,seicento,125000,petrol,fiat,small_car
9988,1800,1998,10,manual,125,passat,150000,petrol,volkswagen,combi
9989,3600,2001,2,manual,102,transporter,150000,diesel,volkswagen,bus
9990,3800,2005,3,manual,90,galaxy,5000,petrol,ford,limousine
9992,2600,2006,3,manual,75,fusion,150000,petrol,ford,small_car
9993,5190,2007,10,manual,105,golf,150000,diesel,volkswagen,limousine
9994,5200,2005,12,manual,90,golf,150000,diesel,volkswagen,bus
9995,2650,2005,1,manual,80,corsa,150000,petrol,opel,small_car
9996,9600,2011,6,manual,140,touran,150000,diesel,volkswagen,bus
9997,1500,1999,0,manual,101,astra,150000,petrol,opel,combi
9998,970,2002,10,manual,58,twingo,150000,petrol,renault,small_car
9999,7990,2012,4,manual,101,megane,60000,petrol,renault,limousine

In [8]:
#Replacing all the 0 month values to 1
df.monthOfRegistration.replace(0,1,inplace=True)
# Making the year and month column to get a single date
Purchase_Datetime=pd.to_datetime(df.yearOfRegistration*10000+df.monthOfRegistration*100+1,format='%Y%m%d')
import time
from datetime import date
import datetime as dt
y=dt.datetime(2018, 11,1)
# Calculating days old by subracting both date fields and converting them into integer
Days_old=(y-Purchase_Datetime)
Days_old=(Days_old / np.timedelta64(1, 'D')).astype(int)
#type(Days_old[1])
df['Days_old']=Days_old
df

,price,yearOfRegistration,monthOfRegistration,gearbox,powerPS,model,kilometer,fuelType,brand,vehicleType,Days_old
1,3500,1996,1,manual,150,3er,125000,petrol,bmw,cabrio,8340
2,2200,1998,1,manual,150,c klasse,150000,petrol,mercedes benz,combi,7609
4,2600,2002,7,automatic,41,fortwo,150000,diesel,smart,cabrio,5967
5,2222,2001,10,manual,143,3er,150000,petrol,bmw,limousine,6240
6,4000,2008,11,manual,69,yaris,125000,petrol,toyota,small_car,3652
7,570,1999,6,manual,180,a4,150000,diesel,audi,combi,7093
8,9999,2005,10,manual,200,golf,150000,petrol,volkswagen,small_car,4779
9,16999,2006,1,manual,131,transporter,150000,diesel,volkswagen,bus,4687
10,11300,2000,3,manual,218,slk,90000,petrol,mercedes benz,cabrio,6819
11,11980,2005,8,automatic,272,andere,125000,petrol,mercedes benz,coupe,4840
12,3999,2006,10,manual,80,golf,100000,petrol,volkswagen,limousine,4414
13,500,1997,1,manual,1256,golf,150000,petrol,audi,small_car,7974
14,3450,2006,11,manual,120,zafira,150000,diesel,opel,bus,4383
16,500,1997,3,manual,60,corsa,150000,petrol,opel,small_car,7915
17,12250,2012,2,automatic,105,golf,50000,petrol,volkswagen,limousine,2465
20,2800,2004,8,manual,50,arosa,70000,petrol,seat,small_car,5205
21,7399,2007,10,automatic,140,passat,150000,diesel,volkswagen,combi,4049
23,2200,2005,1,manual,60,corsa,80000,petrol,opel,small_car,5052
24,5500,2012,4,manual,73,2 reihe,50000,petrol,peugeot,limousine,2405
25,5000,2000,8,manual,150,rav,150000,petrol,toyota,suv,6666
26,17800,2013,9,automatic,163,mondeo,60000,diesel,ford,combi,1887
28,5299,2004,11,manual,105,golf,150000,diesel,volkswagen,limousine,5113
29,1000,1995,12,manual,101,a4,150000,petrol,audi,limousine,8371
30,7800,2005,11,automatic,218,x reihe,150000,diesel,bmw,suv,4748
32,1700,2003,8,manual,83,kalos,100000,petrol,daewoo,small_car,5571
33,750,1994,5,manual,80,corsa,125000,petrol,opel,small_car,8950
34,4200,2003,1,manual,110,a2,150000,petrol,audi,small_car,5783
35,9300,2007,8,manual,205,a4,150000,diesel,audi,combi,4110
36,10500,2005,3,manual,203,a4,150000,diesel,audi,Others,4993
38,5350,2006,10,automatic,163,andere,150000,diesel,hyundai,suv,4414
...,...,...,...,...,...,...,...,...,...,...,...
9966,899,2000,1,manual,50,arosa,150000,petrol,seat,small_car,6879
9968,4700,2006,1,manual,140,golf,150000,diesel,volkswagen,bus,4687
9969,3450,2005,9,manual,110,micra,125000,petrol,nissan,small_car,4809
9970,6350,2004,7,automatic,143,c klasse,150000,petrol,mercedes benz,limousine,5236
9971,990,1999,11,manual,101,astra,150000,petrol,opel,limousine,6940
9972,8495,2006,11,automatic,102,golf,80000,petrol,volkswagen,bus,4383
9973,1650,1996,4,automatic,193,5er,150000,petrol,bmw,limousine,8249
9975,3999,2004,10,manual,226,mondeo,150000,petrol,ford,limousine,5144
9976,5190,2008,4,manual,105,meriva,150000,petrol,opel,bus,3866
9977,2210,2002,11,manual,131,a4,150000,diesel,audi,combi,5844
9979,1499,2002,11,manual,101,andere,150000,petrol,mazda,bus,5844
9980,2399,1998,7,manual,136,e klasse,150000,petrol,mercedes benz,combi,7428
9981,599,1993,4,automatic,75,golf,150000,petrol,volkswagen,small_car,9345
9982,2650,2005,6,manual,52,fox,100000,petrol,volkswagen,small_car,4901
9983,8950,2007,4,manual,200,spider,150000,diesel,alfa romeo,cabrio,4232
9984,15900,2012,4,manual,140,passat,70000,diesel,volkswagen,combi,2405
9985,3250,2005,7,manual,97,zafira,125000,cng,opel,bus,4871
9986,470,1999,1,manual,50,ka,70000,petrol,ford,small_car,7244
9987,450,2001,2,manual,55,seicento,125000,petrol,fiat,small_car,6482
9988,1800,1998,10,manual,125,passat,150000,petrol,volkswagen,combi,7336
9989,3600,2001,2,manual,102,transporter,150000,diesel,volkswagen,bus,6482
9990,3800,2005,3,manual,90,galaxy,5000,petrol,ford,limousine,4993
9992,2600,2006,3,manual,75,fusion,150000,petrol,ford,small_car,4628
9993,5190,2007,10,manual,105,golf,150000,diesel,volkswagen,limousine,4049
9994,5200,2005,12,manual,90,golf,150000,diesel,volkswagen,bus,4718
9995,2650,2005,1,manual,80,corsa,150000,petrol,opel,small_car,5052
9996,9600,2011,6,manual,140,touran,150000,diesel,volkswagen,bus,2710
9997,1500,1999,1,manual,101,astra,150000,petrol,opel,combi,7244
9998,970,2002,10,manual,58,twingo,150000,petrol,renault,small_car,5875
9999,7990,2012,4,manual,101,megane,60000,petrol,renault,limousine,2405

In [9]:
df.drop(columns=['yearOfRegistration','monthOfRegistration','powerPS'],inplace=True)
df

,price,gearbox,model,kilometer,fuelType,brand,vehicleType,Days_old
1,3500,manual,3er,125000,petrol,bmw,cabrio,8340
2,2200,manual,c klasse,150000,petrol,mercedes benz,combi,7609
4,2600,automatic,fortwo,150000,diesel,smart,cabrio,5967
5,2222,manual,3er,150000,petrol,bmw,limousine,6240
6,4000,manual,yaris,125000,petrol,toyota,small_car,3652
7,570,manual,a4,150000,diesel,audi,combi,7093
8,9999,manual,golf,150000,petrol,volkswagen,small_car,4779
9,16999,manual,transporter,150000,diesel,volkswagen,bus,4687
10,11300,manual,slk,90000,petrol,mercedes benz,cabrio,6819
11,11980,automatic,andere,125000,petrol,mercedes benz,coupe,4840
12,3999,manual,golf,100000,petrol,volkswagen,limousine,4414
13,500,manual,golf,150000,petrol,audi,small_car,7974
14,3450,manual,zafira,150000,diesel,opel,bus,4383
16,500,manual,corsa,150000,petrol,opel,small_car,7915
17,12250,automatic,golf,50000,petrol,volkswagen,limousine,2465
20,2800,manual,arosa,70000,petrol,seat,small_car,5205
21,7399,automatic,passat,150000,diesel,volkswagen,combi,4049
23,2200,manual,corsa,80000,petrol,opel,small_car,5052
24,5500,manual,2 reihe,50000,petrol,peugeot,limousine,2405
25,5000,manual,rav,150000,petrol,toyota,suv,6666
26,17800,automatic,mondeo,60000,diesel,ford,combi,1887
28,5299,manual,golf,150000,diesel,volkswagen,limousine,5113
29,1000,manual,a4,150000,petrol,audi,limousine,8371
30,7800,automatic,x reihe,150000,diesel,bmw,suv,4748
32,1700,manual,kalos,100000,petrol,daewoo,small_car,5571
33,750,manual,corsa,125000,petrol,opel,small_car,8950
34,4200,manual,a2,150000,petrol,audi,small_car,5783
35,9300,manual,a4,150000,diesel,audi,combi,4110
36,10500,manual,a4,150000,diesel,audi,Others,4993
38,5350,automatic,andere,150000,diesel,hyundai,suv,4414
...,...,...,...,...,...,...,...,...
9966,899,manual,arosa,150000,petrol,seat,small_car,6879
9968,4700,manual,golf,150000,diesel,volkswagen,bus,4687
9969,3450,manual,micra,125000,petrol,nissan,small_car,4809
9970,6350,automatic,c klasse,150000,petrol,mercedes benz,limousine,5236
9971,990,manual,astra,150000,petrol,opel,limousine,6940
9972,8495,automatic,golf,80000,petrol,volkswagen,bus,4383
9973,1650,automatic,5er,150000,petrol,bmw,limousine,8249
9975,3999,manual,mondeo,150000,petrol,ford,limousine,5144
9976,5190,manual,meriva,150000,petrol,opel,bus,3866
9977,2210,manual,a4,150000,diesel,audi,combi,5844
9979,1499,manual,andere,150000,petrol,mazda,bus,5844
9980,2399,manual,e klasse,150000,petrol,mercedes benz,combi,7428
9981,599,automatic,golf,150000,petrol,volkswagen,small_car,9345
9982,2650,manual,fox,100000,petrol,volkswagen,small_car,4901
9983,8950,manual,spider,150000,diesel,alfa romeo,cabrio,4232
9984,15900,manual,passat,70000,diesel,volkswagen,combi,2405
9985,3250,manual,zafira,125000,cng,opel,bus,4871
9986,470,manual,ka,70000,petrol,ford,small_car,7244
9987,450,manual,seicento,125000,petrol,fiat,small_car,6482
9988,1800,manual,passat,150000,petrol,volkswagen,combi,7336
9989,3600,manual,transporter,150000,diesel,volkswagen,bus,6482
9990,3800,manual,galaxy,5000,petrol,ford,limousine,4993
9992,2600,manual,fusion,150000,petrol,ford,small_car,4628
9993,5190,manual,golf,150000,diesel,volkswagen,limousine,4049
9994,5200,manual,golf,150000,diesel,volkswagen,bus,4718
9995,2650,manual,corsa,150000,petrol,opel,small_car,5052
9996,9600,manual,touran,150000,diesel,volkswagen,bus,2710
9997,1500,manual,astra,150000,petrol,opel,combi,7244
9998,970,manual,twingo,150000,petrol,renault,small_car,5875
9999,7990,manual,megane,60000,petrol,renault,limousine,2405

In [10]:
#cat_cols = ['gearbox','fuelType','brand','vehicleType']
#df = pd.get_dummies(df, columns = cat_cols, drop_first=True)

df_dummies=pd.get_dummies(data=df,columns=['vehicleType','model','brand','gearbox','fuelType'],drop_first=True)
df_dummies.head()

,price,kilometer,Days_old,vehicleType_bus,vehicleType_cabrio,vehicleType_combi,vehicleType_coupe,vehicleType_limousine,vehicleType_small_car,vehicleType_suv,...,brand_toyota,brand_volkswagen,brand_volvo,gearbox_manual,fuelType_diesel,fuelType_electro,fuelType_hybrid,fuelType_lpg,fuelType_others,fuelType_petrol
1,3500,125000,8340,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,2200,150000,7609,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,2600,150000,5967,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,2222,150000,6240,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,1
6,4000,125000,3652,0,0,0,0,0,1,0,...,1,0,0,1,0,0,0,0,0,1

In [11]:
X = df_dummies.drop('price',axis=1)
X.head()

,kilometer,Days_old,vehicleType_bus,vehicleType_cabrio,vehicleType_combi,vehicleType_coupe,vehicleType_limousine,vehicleType_small_car,vehicleType_suv,model_100,...,brand_toyota,brand_volkswagen,brand_volvo,gearbox_manual,fuelType_diesel,fuelType_electro,fuelType_hybrid,fuelType_lpg,fuelType_others,fuelType_petrol
1,125000,8340,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,150000,7609,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,150000,5967,0,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,150000,6240,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1
6,125000,3652,0,0,0,0,0,1,0,0,...,1,0,0,1,0,0,0,0,0,1

In [12]:
y = df_dummies.price
y.head()

1    3500
2    2200
4    2600
5    2222
6    4000
Name: price, dtype: int64

In [13]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [14]:
print (linreg.intercept_)

17115.813566426667

In [15]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.20, random_state=0)
linreg = LinearRegression()
linreg.fit(X_train, y_train)
y_pred = linreg.predict(X_test)
y_pred

array([10881.05424126, -1383.17586846,  9092.72418245, ...,
       10373.53101632,  5038.86553042,  2446.92422549])

In [16]:
from sklearn.metrics import mean_squared_error
from math import sqrt

#rmse = sqrt(mean_squared_error(y_test, y_pred))
rmse=np.sqrt(metrics.mean_squared_error(y_test, y_pred))
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

adj_r2 = 1 - float(len(y)-1)/(len(y)-len(linreg.coef_)-1)*(1 - r2)

#rmse

#y_pred = linreg.predict(X_test)
#print(linreg.score(X_test, y_test)*100,'% Prediction Accuracy')
rmse, r2, adj_r2

(3615.081113325688, 0.6671632515975926, 0.6545534192797988)

In [17]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [18]:
rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)
rfr.score(X_test, y_test)

0.7250923158751686

In [20]:
tree = DecisionTreeRegressor()
tree.fit(X_train, y_train)


#y_pred = tree.predict(X_test)
tree.score(X_test,y_test)

0.5534297254914753